const route = require('express').Router()
const { ForgetPassword } = require('../controllers/UserControllers')
const { getAllUsers } = require('../controllers/UserControllers')
const verifyRoles = require('../middlewares/verifyRoles')
const allowedRoles = require('../config/allowedRoles')
const { Login } = require('../controllers/UserControllers')
const { Logout } = require('../controllers/UserControllers')
const { Reg } = require('../controllers/UserControllers')
const { Report } = require('../controllers/UserControllers')
const { resetPassword } = require('../controllers/UserControllers')
const { UpdatePassword } = require('../controllers/UserControllers')
route.get('/', verifyRoles(allowedRoles.Admin), getAllUsers)
route.post('/reg', Reg)
route.post('/login', Login)
route.post('/forget', ForgetPassword)
route.post('/update_password', UpdatePassword)
route.post('/reset', resetPassword)
route.get('/logout', Logout)
route.post('/report', Report)

module.exports = route
